import { createContext, useContext, useState, ReactNode, useCallback } from 'react';

export type Language = 'en' | 'it';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    toggleLanguage: () => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Navigation
        'nav.home': 'Home',
        'nav.characters': 'Characters',
        'nav.new': 'New',
        'nav.browse': 'Browse',

        // Home Page
        'home.title': 'Pathfinder 2e',
        'home.subtitle': 'Create and manage your Pathfinder Second Edition characters',
        'home.newCharacter': 'New Character',
        'home.myCharacters': 'My Characters',
        'home.createCharacter': 'Create Character',
        'home.loadCharacter': 'Load Character',
        'home.classes': 'Classes',
        'home.ancestries': 'Ancestries',
        'home.backgrounds': 'Backgrounds',
        'home.viewAll': 'View all →',
        'home.features': 'Features',
        'home.feature.wizard': 'Guided Creation',
        'home.feature.wizardDesc': 'Step-by-step wizard to create complete characters',
        'home.feature.responsive': 'Responsive',
        'home.feature.responsiveDesc': 'Works perfectly on PC and mobile devices',
        'home.feature.bilingual': 'Bilingual',
        'home.feature.bilingualDesc': 'Interface available in English and Italian',

        // Character List
        'characters.title': 'My Characters',
        'characters.saved': 'saved characters',
        'characters.empty.title': 'No Characters',
        'characters.empty.description': 'You haven\'t created any characters yet. Start by creating your first hero!',
        'characters.create': 'Create Character',
        'characters.modified': 'Modified',

        // Character Builder
        'builder.choose': 'Choose',
        'builder.ancestry': 'Ancestry',
        'builder.heritage': 'Heritage',
        'builder.background': 'Background',
        'builder.class': 'Class',
        'builder.classSpecialization': 'Class Specialization',
        'builder.secondaryClass': 'Secondary Class',
        'builder.notSelected': 'Not Selected',
        'builder.abilities': 'Abilities',
        'builder.summary': 'Summary',
        'builder.search': 'Search...',
        'builder.searchAncestry': 'Search ancestry...',
        'builder.searchBackground': 'Search background...',
        'builder.searchClass': 'Search class...',
        'builder.chooseAncestry': 'Choose Ancestry',
        'builder.chooseHeritage': 'Choose Heritage for',
        'builder.noHeritage.title': 'No Heritage Available',
        'builder.noHeritage.desc': 'There are no specific heritages for this ancestry. You can proceed to the next step.',
        'builder.chooseBackground': 'Choose Background',
        'builder.chooseClass': 'Choose Class',
        'builder.abilityScores': 'Ability Scores',
        'builder.abilityScoresDesc': 'Assign your character\'s base scores. You can use values between 8 and 18.',
        'builder.modifier': 'Modifier',
        'builder.characterSummary': 'Character Summary',
        'builder.characterName': 'Character Name',
        'builder.enterName': 'Enter name...',
        'builder.abilityBoosts': 'Ability Boosts',
        'builder.abilityFlaws': 'Ability Flaws',
        'builder.hitPoints': 'Hit Points',
        'builder.speed': 'Speed',
        'builder.level': 'Level',
        'builder.save': '💾 Save Character',
        'builder.next': 'Next →',
        'builder.back': '← Back',
        'builder.continue': 'Continue →',
        'builder.skillTraining': 'Skill Training',
        'builder.classSkillSlots': 'Class Skill Slots',
        'builder.intBonus': 'INT Bonus',
        'builder.totalSlots': 'Total Slots',
        'builder.selected': 'Selected',
        'builder.autoTrainedSkills': 'Class-Trained Skills',
        'builder.chooseSkills': 'Choose Additional Skills',
        'builder.levelUpBoosts': 'Level-Up Boosts',
        'builder.skillIncrease': 'Skill Increase',
        'builder.generalFeat': 'General Feat',
        'builder.skillFeat': 'Skill Feat',

        // Abilities
        'ability.str': 'Strength',
        'ability.dex': 'Dexterity',
        'ability.con': 'Constitution',
        'ability.int': 'Intelligence',
        'ability.wis': 'Wisdom',
        'ability.cha': 'Charisma',

        // Browse
        'browse.title': 'Browse Content',
        'browse.subtitle': 'Explore ancestries, classes, feats and more',
        'browse.ancestries': 'Ancestries',
        'browse.classes': 'Classes',
        'browse.backgrounds': 'Backgrounds',
        'browse.feats': 'Feats',
        'browse.spells': 'Spells',
        'browse.equipment': 'Equipment',
        'browse.underConstruction': 'Under Construction',
        'browse.comingSoon': 'This section will be available soon!',
        'browse.features': 'Features',
        'browse.proficiencies': 'Proficiencies',
        'browse.perception': 'Perception',
        'browse.fortitude': 'Fortitude',
        'browse.reflex': 'Reflex',
        'browse.will': 'Will',
        'browse.classFeatures': 'Class Features',
        'browse.skillTraining': 'Skill Training',

        // Common
        'common.hp': 'HP',
        'common.speed': 'Speed',
        'common.size': 'Size',
        'common.martial': 'Martial',

        // Desktop Layout
        'nav.menu': 'Menu',
        'character.unnamed': 'Unknown Adventurer',
        'character.noClass': 'No Class',
        'character.level': 'Level',
        'actions.rest': 'Rest',
        'actions.addCondition': 'Add Condition',
        'actions.addCustomBuff': 'Add Custom Buff',
        'actions.addWeapon': 'Add Weapon',
        'actions.cancel': 'Cancel',
        'actions.apply': 'Apply',
        'actions.select': 'Select',
        'actions.close': 'Close',

        // Stats
        'stats.speed': 'Speed',
        'stats.size': 'Size',
        'stats.perception': 'Perception',
        'stats.heroPoints': 'Hero Points',
        'stats.classDC': 'Class DC',

        // HP Management
        'hp.damage': 'Damage',
        'hp.heal': 'Heal',
        'hp.temporary': 'Temp HP',
        'hp.custom': 'Custom',
        'hp.apply': 'Apply',
        'hp.manageTitle': 'Manage Hit Points',
        'hp.clickToManage': 'Click to manage HP',
        'hp.quickAdjust': 'Quick Adjust',
        'hp.customHP': 'Custom HP',
        'hp.customValue': 'Enter value (negative for damage)',
        'hp.tempHP': 'Temporary HP',
        'hp.tempValue': 'Set temp HP',
        'hp.clear': 'Clear',
        'hp.currentTemp': 'Current',

        // Tabs
        'tabs.weapons': 'Weapons',
        'tabs.defense': 'Defense',
        'tabs.gear': 'Gear',
        'tabs.spells': 'Spells',
        'tabs.pets': 'Pets',
        'tabs.biography': 'Biography',
        'tabs.notes': 'Notes',
        'tabs.details': 'Details',
        'tabs.feats': 'Feats',
        'tabs.actions': 'Actions',

        // Builder Desktop
        'builder.ancestryFeat': 'Ancestry Feat',
        'builder.classFeat': 'Class Feat',
        'builder.archetypeFeat': 'Archetype Feat',
        'builder.abilityBoost': 'Ability Boost',
        'builder.futureChoices': 'Future choices...',
        'builder.noWeapons': 'No weapons equipped. Add a weapon to get started.',
        'builder.addWeaponHint': 'Add a weapon to calculate attack bonuses.',
        'builder.noGear': 'No gear in inventory.',
        'builder.addGearHint': 'Add equipment, consumables, and treasure.',
        'builder.noSpellcasting': 'This character is not a spellcaster.',
        'builder.noSpellsKnown': 'No spells known yet.',
        'builder.noFeats': 'No feats selected yet.',
        'builder.addFeatHint': 'Select feats from the build sidebar.',
        'builder.noNotes': 'No notes yet.',
        'builder.noResistances': 'None',

        // Stats Extended
        'stats.armorClass': 'Armor Class',
        'stats.attack': 'Attack',
        'stats.damage': 'Damage',
        'stats.hands': 'Hands',
        'stats.bulk': 'Bulk',
        'stats.currency': 'Currency',
        'stats.invested': 'Invested',
        'stats.base': 'Base',
        'stats.proficiency': 'Prof',
        'stats.armor': 'Armor',
        'stats.savingThrows': 'Saving Throws',
        'stats.resistances': 'Resistances & Immunities',
        'stats.level': 'Level',
        'stats.tradition': 'Tradition',
        'stats.spellAttack': 'Spell Attack',
        'stats.spellDC': 'Spell DC',
        'stats.focusPoints': 'Focus Points',
        'stats.spellSlots': 'Spell Slots',
        'stats.rank': 'Rank',
        'stats.knownSpells': 'Known Spells',

        // Saves
        'saves.fortitude': 'Fortitude',
        'saves.reflex': 'Reflex',
        'saves.will': 'Will',

        // Defense
        'defense.resistances': 'Resistances & Immunities',
        'defense.noResistances': 'None',
        'defense.addResistance': 'Add Resistance',
        'defense.addImmunity': 'Add Immunity',
        'defense.type': 'Type',
        'defense.value': 'Value',
        'defense.selectType': 'Select type...',

        // Spellcasting
        'spellcasting.spellDC': 'Spell DC',
        'spellcasting.spellAttack': 'Spell Attack',
        'spellcasting.tradition': 'Tradition',
        'spellcasting.keyAbility': 'Key Ability',

        // Actions Extended
        'actions.strike': 'Strike',
        'actions.details': 'Details',
        'actions.addGear': 'Add Gear',
        'actions.addSpell': 'Add Spell',
        'actions.cast': 'Cast',
        'actions.action': 'Action',
        'actions.actions': 'Actions',
        'actions.free': 'Free',
        'actions.reaction': 'Reaction',

        // Filters
        'filters.all': 'All',
        'filters.cost': 'Cost',
        'filters.category': 'Category',
        'filters.basic': 'Basic',
        'filters.skill': 'Skill',
        'filters.class': 'Class',
        'filters.interaction': 'Interaction',
        'filters.offense': 'Offense',
        'filters.movement': 'Movement',
        'filters.feat': 'Feat',
        'filters.pet': 'Pet',

        // Status
        'status.encumbered': 'Encumbered',
        'status.overloaded': 'Overloaded',
        'status.worn': 'Worn',

        // Feats Categories
        'feats.ancestry': 'Ancestry Feats',
        'feats.class': 'Class Feats',
        'feats.general': 'General Feats',
        'feats.skill': 'Skill Feats',
        'feats.bonus': 'Bonus Feats',
        'feats.total': 'total',

        // Reference
        'reference.attackBonus': 'Attack Bonus Reference',

        // Character
        'character.name': 'Name',
        'character.player': 'Player',
        'character.notes': 'Notes',
        'character.alignment': 'Alignment',
        'character.selectAlignment': 'Select Alignment',

        // Weapons
        'weapons.attack': 'Attack',
        'weapons.firstAttack': 'First Attack',
        'weapons.secondAttack': 'Second Attack (MAP)',
        'weapons.thirdAttack': 'Third Attack (MAP)',
        'weapons.twoHandToggle': 'Two-Hand Mode',
        'weapons.map': 'MAP (Multiple Attack Penalty)',
        'weapons.options': 'Weapon Options',
        'weapons.fundamentalRunes': 'Fundamental Runes',
        'weapons.potencyRune': 'Potency Rune',
        'weapons.potency': 'Potency',
        'weapons.greaterPotency': 'Greater Potency',
        'weapons.majorPotency': 'Major Potency',
        'weapons.strikingRune': 'Striking Rune',
        'weapons.striking': 'Striking',
        'weapons.greaterStriking': 'Greater Striking',
        'weapons.majorStriking': 'Major Striking',
        'weapons.propertyRunes': 'Property Runes',
        'weapons.enterRuneName': 'Enter rune name...',
        'weapons.addPropertyRune': 'Add Property Rune',
        'weapons.materialPhysical': 'Material & Physical',
        'weapons.material': 'Material',
        'weapons.isLarge': 'Large Weapon',
        'weapons.bulkOverride': 'Bulk Override',
        'weapons.advancedCustomization': 'Advanced Customization',
        'weapons.attackAbility': 'Attack Ability',
        'weapons.auto': 'Auto (Default)',
        'weapons.customName': 'Custom Name',
        'weapons.bonusAttack': 'Bonus Attack',
        'weapons.bonusDamage': 'Bonus Damage',
        'weapons.customDamageType': 'Custom Damage Type',
        'weapons.criticalSpecialization': 'Critical Specialization',
        'weapons.totalPrice': 'Total Price',
        'weapons.none': 'None',
        'weapons.rollAttack': 'Roll Attack',
        'materials.coldIron': 'Cold Iron',
        'materials.silver': 'Silver',
        'materials.adamantine': 'Adamantine',
        'materials.orichalcum': 'Orichalcum',
        'materials.mithral': 'Mithral',

        // Armor
        'armor.potencyRune': 'Armor Potency Rune',
        'armor.resilientRune': 'Resilient Rune',
        'armor.propertyRunes': 'Property Runes',
        'armor.addPropertyRune': 'Add Property Rune',
        'armor.advancedCustomization': 'Advanced Customization',
        'armor.customName': 'Custom Name',
        'armor.bonusAC': 'Bonus AC',
        'armor.checkPenaltyOverride': 'Check Penalty Override',
        'armor.speedPenaltyOverride': 'Speed Penalty Override',
        'armor.dexCapOverride': 'Dex Cap Override',
        'armor.totalPrice': 'Total Price',
        'armor.options': 'Armor Options',

        // Shield
        'shield.reinforcingRune': 'Reinforcing Rune',
        'shield.propertyRunes': 'Property Runes',
        'shield.addPropertyRune': 'Add Property Rune',
        'shield.advancedCustomization': 'Advanced Customization',
        'shield.customName': 'Custom Name',
        'shield.hardnessOverride': 'Hardness Override',
        'shield.maxHPOverride': 'Max HP Override',
        'shield.currentHP': 'Current HP',
        'shield.broken': 'Broken',
        'shield.totalPrice': 'Total Price',
        'shield.options': 'Shield Options',

        // Equipment
        'equipment.armor': 'Armor',
        'equipment.shield': 'Shield',
        'actions.equipArmor': 'Equip Armor',
        'actions.equipShield': 'Equip Shield',
        'actions.equip': 'Equip',
        'actions.wield': 'Wield',
        'actions.unequip': 'Unequip',
        'browser.equipment': 'Equipment Browser',
        'browser.search': 'Search...',
        'browser.selectItem': 'Select an item to view details',

        // Pets & Companions
        'pets.title': 'Pets & Companions',
        'pets.empty': 'No pets or companions yet. Add a familiar, animal companion, or eidolon to your character.',
        'pets.add': 'Add Pet',
        'pets.type': 'Type',
        'pets.level': 'Level',
        'pets.hp': 'HP',
        'pets.ac': 'AC',
        'pets.perception': 'Perception',
        'pets.saves': 'Saves',
        'pets.speed': 'Speed',
        'pets.attacks': 'Attacks',
        'pets.abilities': 'Abilities',
        'pets.evolutions': 'Evolutions',
        'pets.notes': 'Notes',
        'pets.edit': 'Edit',
        'pets.delete': 'Delete',
        'pets.confirmDelete': 'Are you sure you want to remove this pet?',
        'pets.familiar': 'Familiar',
        'pets.animalCompanion': 'Animal Companion',
        'pets.eidolon': 'Eidolon',
        'pets.selectType': 'Select Pet Type',
        'pets.enterName': 'Enter name...',
        'pets.animal.companionType': 'Companion Type',
        'pets.animal.size': 'Size',
        'pets.eidolon.evolutionPoints': 'Evolution Points',
        'pets.eidolon.sharesHP': 'Shares HP with Summoner',
        'pets.familiar.abilities': 'Familiar Abilities',
        'pets.familiar.selectAbilities': 'Select up to 2 abilities',
        'pets.familiar.addAbility': 'Add Ability',
        'pets.stats': 'Stats',
        'pets.masterLevel': 'Master Level',
        'pets.conMod': 'CON Mod',
        'pets.actions.petActions': 'Pet Actions',
        'pets.actions.familiarAbility': 'Use Familiar Ability',
        'pets.actions.companionAttack': 'Companion Attack',
        'pets.actions.eidolanEvolution': 'Use Evolution',
        'pets.size.tiny': 'Tiny',
        'pets.size.small': 'Small',
        'pets.size.medium': 'Medium',
        'pets.size.large': 'Large',
        'pets.proficiency.untrained': 'Untrained',
        'pets.proficiency.trained': 'Trained',
        'pets.proficiency.expert': 'Expert',
        'pets.proficiency.master': 'Master',
        'pets.proficiency.legendary': 'Legendary',

        // Crafting & Formula Book
        'crafting.title': 'Crafting',
        'crafting.formulas': 'Formula Book',
        'crafting.projects': 'Crafting Projects',
        'crafting.dailyItems': 'Daily Items',
        'crafting.addFormula': 'Add Formula',
        'crafting.newProject': 'New Project',
        'crafting.startProject': 'Start Crafting',
        'crafting.daysSpent': 'Days Spent',
        'crafting.progress': 'Progress',
        'crafting.targetValue': 'Cost (sp)',
        'crafting.complete': 'Complete',
        'crafting.collectItem': 'Collect Item',
        'crafting.addDay': 'Add Day of Work',
        'crafting.bulk': 'Bulk',
        'crafting.price': 'Price',
        'crafting.level': 'Level',
        'crafting.craftingSuccess': 'Crafting Success!',
        'crafting.craftingError': 'Crafting Error',
        'crafting.notEnoughGold': 'Not enough gold to complete crafting',
        'crafting.projectCompleted': 'Project completed! Item added to inventory.',
        'crafting.emptyFormulas': 'No formulas learned yet.',
        'crafting.emptyProjects': 'No active crafting projects.',
        'crafting.emptyDailyItems': 'No daily items created.',
        'crafting.formulaAdded': 'Formula added to book.',
        'crafting.formulaRemoved': 'Formula removed from book.',
        'crafting.confirmComplete': 'Complete this project? This will deduct the required gold.',
        'crafting.proficiencyBonus': 'Proficiency Bonus',
        'crafting.costReduction': 'Cost Reduction per Day',

        // Container System
        'inventory.containers': 'Containers',
        'inventory.root': 'Root Inventory',
        'inventory.moveToContainer': 'Move to Container',
        'inventory.removeFromContainer': 'Remove from Container',
        'inventory.bulkUsed': 'Bulk Used',
        'inventory.bulkMax': 'Max Bulk',
        'inventory.encumbered': 'Encumbered',
        'inventory.lightItems': 'Light Items',
        'inventory.capacity': 'Capacity',
        'inventory.bulkReduction': 'Bulk Reduction',
        'inventory.selectContainer': 'Select Container',

        // Tooltip & Calculation Breakdown
        'tooltip.base': 'Base',
        'tooltip.ability': 'Ability',
        'tooltip.proficiency': 'Proficiency',
        'tooltip.item': 'Item',
        'tooltip.buff': 'Buff',
        'tooltip.penalty': 'Penalty',
        'tooltip.total': 'Total',
        'theme.dark': 'Dark Mode',
        'theme.light': 'Light Mode',

        // Variant Rules
        'menu.variantRules': 'Variant Rules',
        'menu.configureVariantRules': 'Configure Variant Rules',
        'menu.activeVariantRules': 'active',

        // Focus Points
        'focus.refocusNote': 'Use Refocus during daily preparations to recover Focus Points.',
        'actions.spendFocus': 'Spend Focus Point',
        'actions.recoverFocus': 'Recover Focus Point',
        'actions.refocus': 'Refocus',
        'actions.spend': 'Spend',
        'actions.recover': 'Recover',
        'actions.change': 'Change',
        'actions.remove': 'Remove',

        // Rituals
        'tabs.rituals': 'Rituals',
        'rituals.browser': 'Ritual Browser',
        'rituals.noRituals': 'No rituals known.',
        'rituals.castTime': 'Cast Time',
        'rituals.primaryCheck': 'Primary Check',
        'rituals.secondaryCheck': 'Secondary Check',
        'rituals.cost': 'Cost',
        'rituals.primary': 'Primary',
        'rituals.secondary': 'Secondary',
        'actions.browseRituals': 'Browse Rituals',
        'actions.learnRitual': 'Learn Ritual',
        'actions.removeRitual': 'Remove Ritual',
        'rituals.alreadyKnown': 'Already Known',
        'filter.all': 'All',

        // Magical Items (Staves & Wands)
        'magicalItems.staves': 'Staves',
        'magicalItems.wands': 'Wands',
        'magicalItems.charges': 'Charges',
        'magicalItems.spells': 'Spells',
        'magicalItems.prepareStaff': 'Prepare Staff',
        'magicalItems.prepare': 'Prepare',
        'magicalItems.castFromStaff': 'Cast from Staff',
        'magicalItems.dailyUses': 'Daily Uses',
        'magicalItems.depleted': 'Depleted',
        'magicalItems.castFromWand': 'Cast from Wand',
        'magicalItems.cast': 'Cast',
        'magicalItems.overchargeRisk': 'Overcharge Risk',
        'magicalItems.castOvercharge': 'Cast (Overcharge)',
        'magicalItems.noMagicalItems': 'No magical items equipped.',
        'magicalItems.addStavesWands': 'Add Staves or Wands to your equipment to manage their magical properties.',
        'magicalItems.overchargeWarning': 'Overcharge Warning',
        'magicalItems.overchargeWarningText': 'Using this wand again today requires overcharging it. This risks damaging or destroying the wand.',
        'magicalItems.overchargeDC': 'Overcharge DC',
        'magicalItems.onFailure': 'On Failure',
        'magicalItems.wandTakesDamage': 'Wand takes damage',
        'magicalItems.onCriticalFailure': 'On Critical Failure',
        'magicalItems.wandDestroyed': 'Wand is destroyed',
        'magicalItems.riskOvercharge': 'Risk Overcharge',

        // Search & Browse
        'search.placeholder': 'Search...',
        'actions.browseSpells': 'Browse Spells',
        'actions.learnSpell': 'Learn Spell',

        // Dice Roller
        'dice.roll': 'Roll',
        'dice.total': 'Total',
        'dice.history': 'Roll History',
        'dice.clearHistory': 'Clear History',
        'dice.noRolls': 'No rolls yet.',
        'dice.rolls': 'rolls',
        'dice.clickToClose': 'Click anywhere to close',
        'dice.criticalSuccess': 'CRITICAL SUCCESS!',
        'dice.criticalFailure': 'CRITICAL FAILURE!',
        'dice.attackRoll': 'Attack Roll',
        'dice.damageRoll': 'Damage Roll',
        'dice.saveRoll': 'Save Roll',
        'dice.skillCheck': 'Skill Check',
        'dice.perceptionCheck': 'Perception Check',
        'dice.initiative': 'Initiative',
        'dice.crit': 'Crit',
        'dice.3dEnable': 'Enable 3D Dice',
        'dice.3dDisable': 'Disable 3D Dice',

        // Biography & Appearance
        'biography.title': 'Biography & Appearance',
        'biography.quickStats': 'Quick Stats',
        'biography.age': 'Age',
        'biography.gender': 'Gender',
        'biography.pronouns': 'Pronouns',
        'biography.height': 'Height',
        'biography.weight': 'Weight',
        'biography.ethnicity': 'Ethnicity',
        'biography.nationality': 'Nationality',
        'biography.birthplace': 'Birthplace',
        'biography.appearance': 'Physical Appearance',
        'biography.personality': 'Personality & Attitude',
        'biography.beliefs': 'Beliefs & Philosophy',
        'biography.likes': 'Likes',
        'biography.dislikes': 'Dislikes',
        'biography.catchphrases': 'Memorable Quotes',
        'biography.avatarUrl': 'Image URL',
        'biography.genderPlaceholder': 'Male, Female, Non-binary...',
        'biography.ethnicityPlaceholder': 'Human, Elf, Dwarf...',
        'biography.nationalityPlaceholder': 'Chelish, Taldan, Varisian...',
        'biography.birthplacePlaceholder': 'Magnimar, Sandpoint, Westcrown...',
        'biography.appearancePlaceholder': 'Describe your character\'s physical appearance... Hair color, eye color, distinguishing features, clothing style, etc.',
        'biography.personalityPlaceholder': 'Describe your character\'s personality... Traits, mannerisms, how they interact with others, etc.',
        'biography.beliefsPlaceholder': 'Describe your character\'s beliefs... Religious views, philosophy, moral code, etc.',
        'biography.likesPlaceholder': 'What does your character enjoy?',
        'biography.dislikesPlaceholder': 'What does your character hate or fear?',
        'biography.catchphrasesPlaceholder': 'Famous quotes, catchphrases, or things your character often says...',

        // Deity
        'deity.selectDeity': 'Select Deity',
        'deity.searchDeities': 'Search deities...',
        'deity.allFonts': 'All Fonts',
        'deity.fontHeal': 'Heal',
        'deity.fontHarm': 'Harm',
        'deity.fontBoth': 'Both',
        'deity.font': 'Font',
        'deity.favoredWeapon': 'Favored Weapon',
        'deity.skill': 'Divine Skill',
        'deity.domains': 'Domains',
        'deity.edicts': 'Edicts',
        'deity.anathema': 'Anathema',
        'deity.select': 'Select',
        'deity.setYourAlignment': 'Set your alignment first',

        // Specialization
        'specialization.title': 'Class Specialization',
        'specialization.notAvailable': 'This class does not have a specialization option.',
        'specialization.selectPrompt': 'Select a specialization from the list to view details.',

        // Commander
        'commander.tactics': 'Tactics',
        'commander.selectTactics': 'Select Tactics',
        'commander.tier': 'Tier',
        'commander.category': 'Category',
        'commander.allTiers': 'All Tiers',
        'commander.basic': 'Basic (Level 1+)',
        'commander.expert': 'Expert (Level 7+)',
        'commander.master': 'Master (Level 15+)',
        'commander.legendary': 'Legendary (Level 19+)',
        'commander.allCategories': 'All Categories',
        'commander.mobility': 'Mobility',
        'commander.offensive': 'Offensive',
        'commander.all': 'All',
        'commander.prepared': 'Prepared',
        'commander.known': 'Known',
        'commander.noTacticsAvailable': 'No tactics available with current filters.',
        'commander.noPreparedTactics': 'No tactics prepared yet.',
        'commander.noTactics': 'No tactics available.',
        'commander.tacticsSelected': 'tactics selected',
        'commander.prepare': 'Prepare',
        'commander.unprepare': 'Unprepare',
        'commander.cost': 'Cost',
        'commander.tacticsBasic': 'Basic Tactics',
        'commander.tacticsExpert': 'Expert Tactics',
        'commander.tacticsMaster': 'Master Tactics',
        'commander.tacticsLegendary': 'Legendary Tactics',
        'commander.dailyTactics': 'Daily Tactics',
        'commander.noKnownTactics': 'No tactics selected yet. Go to level selection to choose your tactics.',

        // Resources
        'resources.title': 'Resources',
        'resources.add': 'Add',
        'resources.addResource': 'Add Custom Resource',
        'resources.name': 'Name',
        'resources.namePlaceholder': 'e.g., Channel Energy, Rage, etc.',
        'resources.maxUses': 'Max Uses',
        'resources.frequency': 'Frequency',
        'resources.daily': 'Daily',
        'resources.perEncounter': 'Per Encounter',
        'resources.resetDaily': 'Reset all daily resources',
        'resources.resetDailyShort': 'Reset Daily',
        'resources.resetEncounter': 'Reset all encounter resources',
        'resources.resetEncounterShort': 'Reset Encounter',
        'resources.empty': 'No custom resources yet. Add abilities or items with limited uses.',
        'resources.loadClassResources': 'Load automatic class resources',
        'resources.loadClassResourcesShort': 'Load Class Resources',

        // Notes
        'notes.edit': 'Edit',
        'notes.preview': 'Preview',
        'notes.startTyping': 'Start typing...',
        'notes.addSection': 'Add Section',
        'notes.sectionTitle': 'Section Title:',

        // Kineticist
        'kineticist.gatesThreshold': "Gate's Threshold",
        'kineticist.choosePath': 'Choose Your Path',
        'kineticist.gatesThresholdDescription': 'At this level, your connection to the elemental planes deepens. Choose how to expand your power:',
        'kineticist.expandThePortal': 'Expand the Portal',
        'kineticist.expandThePortalDesc': 'Choose a junction from your current element(s), gaining access to new impulses.',
        'kineticist.learnImpulse': 'Learn Impulse',
        'kineticist.learnImpulseDesc': 'Learn a new impulse from your current element(s)',
        'kineticist.learnImpulseDescFull': 'Learn a new impulse feat from your current element(s). You can select this impulse in the feats section.',
        'kineticist.learnImpulseDescription': 'You will be able to select a new impulse feat from your current element(s) in the feats selection.',
        'kineticist.forkThePath': 'Fork the Path',
        'kineticist.forkThePathDesc': 'Choose a new element and gain 1 impulse',
        'kineticist.forkThePathFullDescription': 'You are choosing to expand your elemental mastery by adding a new element.',
        'kineticist.selectJunctionPrompt': 'Select 1 junction from your current element(s).',
        'kineticist.currentElements': 'Current Elements',
        'kineticist.selected': 'Selected',
        'kineticist.newElement': 'New Element',
        'kineticist.selectedImpulse': 'Selected Impulse',
        'kineticist.selectNewElement': 'Select New Element',
        'kineticist.selectImpulse': 'Select 1 Impulse',
        'kineticist.availableImpulses': 'Available Impulses',
        'kineticist.junctionSelected': 'junction selected',
        'kineticist.impulseFeats': 'Impulse Feats',

        // Gear Panel - Restore and Swap
        'gear.restore': 'Restore',
        'gear.swap': 'Swap',
        'gear.restoreToDefense': 'Restore to Defense',
        'gear.swapWithDefense': 'Swap with Defense',
        'gear.alreadyEquippedWarning': 'Already Equipped',
        'gear.armorAlreadyEquipped': 'There is already an armor equipped in the Defense slot. Please unequip it first before restoring this one.',
        'gear.shieldAlreadyEquipped': 'There is already a shield equipped in the Defense slot. Please unequip it first before restoring this one.',
        'gear.restoreSuccess': 'Restored to Defense slot',
        'actions.stow': 'Stow',
    },
    it: {
        // Navigation
        'nav.home': 'Home',
        'nav.characters': 'Personaggi',
        'nav.new': 'Nuovo',
        'nav.browse': 'Sfoglia',

        // Home Page
        'home.title': 'Pathfinder 2e',
        'home.subtitle': 'Crea e gestisci i tuoi personaggi per Pathfinder Second Edition',
        'home.newCharacter': 'Nuovo Personaggio',
        'home.myCharacters': 'I Miei Personaggi',
        'home.createCharacter': 'Crea Personaggio',
        'home.loadCharacter': 'Carica Personaggio',
        'home.classes': 'Classi',
        'home.ancestries': 'Stirpi',
        'home.backgrounds': 'Background',
        'home.viewAll': 'Vedi tutte →',
        'home.features': 'Funzionalità',
        'home.feature.wizard': 'Creazione Guidata',
        'home.feature.wizardDesc': 'Wizard passo-passo per creare personaggi completi',
        'home.feature.responsive': 'Responsive',
        'home.feature.responsiveDesc': 'Funziona perfettamente su PC e dispositivi mobili',
        'home.feature.bilingual': 'Bilingue',
        'home.feature.bilingualDesc': 'Interfaccia disponibile in italiano e inglese',

        // Character List
        'characters.title': 'I Miei Personaggi',
        'characters.saved': 'personaggi salvati',
        'characters.empty.title': 'Nessun Personaggio',
        'characters.empty.description': 'Non hai ancora creato nessun personaggio. Inizia creando il tuo primo eroe!',
        'characters.create': 'Crea Personaggio',
        'characters.modified': 'Modificato',

        // Character Builder
        'builder.choose': 'Scegli',
        'builder.ancestry': 'Stirpe',
        'builder.heritage': 'Retaggio',
        'builder.background': 'Background',
        'builder.class': 'Classe',
        'builder.classSpecialization': 'Specializzazione di Classe',
        'builder.secondaryClass': 'Classe Secondaria',
        'builder.notSelected': 'Non Selezionato',
        'builder.abilities': 'Caratteristiche',
        'builder.summary': 'Riepilogo',
        'builder.search': 'Cerca...',
        'builder.searchAncestry': 'Cerca stirpe...',
        'builder.searchBackground': 'Cerca background...',
        'builder.searchClass': 'Cerca classe...',
        'builder.chooseAncestry': 'Scegli la Stirpe',
        'builder.chooseHeritage': 'Scegli il Retaggio per',
        'builder.noHeritage.title': 'Nessun Retaggio Disponibile',
        'builder.noHeritage.desc': 'Non ci sono retaggi specifici per questa stirpe. Puoi procedere al passo successivo.',
        'builder.chooseBackground': 'Scegli il Background',
        'builder.chooseClass': 'Scegli la Classe',
        'builder.abilityScores': 'Punteggi di Caratteristica',
        'builder.abilityScoresDesc': 'Assegna i punteggi base del tuo personaggio. Puoi usare valori tra 8 e 18.',
        'builder.modifier': 'Modificatore',
        'builder.characterSummary': 'Riepilogo Personaggio',
        'builder.characterName': 'Nome del Personaggio',
        'builder.enterName': 'Inserisci il nome...',
        'builder.abilityBoosts': 'Incrementi di Caratteristica',
        'builder.abilityFlaws': 'Difetti di Caratteristica',
        'builder.hitPoints': 'Punti Ferita',
        'builder.speed': 'Velocità',
        'builder.level': 'Livello',
        'builder.save': '💾 Salva Personaggio',
        'builder.next': 'Avanti →',
        'builder.back': '← Indietro',
        'builder.continue': 'Continua →',
        'builder.skillTraining': 'Addestramento Abilità',
        'builder.classSkillSlots': 'Slot Abilità Classe',
        'builder.intBonus': 'Bonus INT',
        'builder.totalSlots': 'Slot Totali',
        'builder.selected': 'Selezionate',
        'builder.autoTrainedSkills': 'Abilità dalla Classe',
        'builder.chooseSkills': 'Scegli Abilità Aggiuntive',
        'builder.levelUpBoosts': 'Incrementi di Livello',
        'builder.skillIncrease': 'Aumento Abilità',
        'builder.generalFeat': 'Talento Generale',
        'builder.skillFeat': 'Talento di Abilità',

        // Abilities
        'ability.str': 'Forza',
        'ability.dex': 'Destrezza',
        'ability.con': 'Costituzione',
        'ability.int': 'Intelligenza',
        'ability.wis': 'Saggezza',
        'ability.cha': 'Carisma',

        // Browse
        'browse.title': 'Sfoglia Contenuti',
        'browse.subtitle': 'Esplora stirpi, classi, talenti e altro',
        'browse.ancestries': 'Stirpi',
        'browse.classes': 'Classi',
        'browse.backgrounds': 'Background',
        'browse.feats': 'Talenti',
        'browse.spells': 'Incantesimi',
        'browse.equipment': 'Equipaggiamento',
        'browse.underConstruction': 'In Costruzione',
        'browse.comingSoon': 'Questa sezione sarà disponibile presto!',
        'browse.features': 'Caratteristiche',
        'browse.proficiencies': 'Competenze',
        'browse.perception': 'Percezione',
        'browse.fortitude': 'Tempra',
        'browse.reflex': 'Riflessi',
        'browse.will': 'Volontà',
        'browse.classFeatures': 'Caratteristiche di Classe',
        'browse.skillTraining': 'Addestramento Abilità',

        // Common
        'common.hp': 'PF',
        'common.speed': 'Velocità',
        'common.size': 'Taglia',
        'common.martial': 'Marziale',

        // Desktop Layout
        'nav.menu': 'Menu',
        'character.unnamed': 'Avventuriero Sconosciuto',
        'character.noClass': 'Nessuna Classe',
        'character.level': 'Livello',
        'actions.rest': 'Riposo',
        'actions.addCondition': 'Aggiungi Condizione',
        'actions.addCustomBuff': 'Aggiungi Bonus',
        'actions.addWeapon': 'Aggiungi Arma',
        'actions.cancel': 'Annulla',
        'actions.apply': 'Applica',
        'actions.select': 'Seleziona',
        'actions.close': 'Chiudi',

        // Stats
        'stats.speed': 'Velocità',
        'stats.size': 'Taglia',
        'stats.perception': 'Percezione',
        'stats.heroPoints': 'Punti Eroe',
        'stats.classDC': 'CD di Classe',

        // HP Management
        'hp.damage': 'Danno',
        'hp.heal': 'Cura',
        'hp.temporary': 'PF Temp',
        'hp.custom': 'Personalizzato',
        'hp.apply': 'Applica',
        'hp.manageTitle': 'Gestisci Punti Ferita',
        'hp.clickToManage': 'Clicca per gestire PF',
        'hp.quickAdjust': 'Regolazione Veloce',
        'hp.customHP': 'PF Personalizzati',
        'hp.customValue': 'Inserisci valore (negativo per danno)',
        'hp.tempHP': 'PF Temporanei',
        'hp.tempValue': 'Imposta PF temporanei',
        'hp.clear': 'Cancella',
        'hp.currentTemp': 'Attuale',

        // Tabs
        'tabs.weapons': 'Armi',
        'tabs.defense': 'Difesa',
        'tabs.gear': 'Equipaggiamento',
        'tabs.spells': 'Incantesimi',
        'tabs.pets': 'Compagni',
        'tabs.biography': 'Biografia',
        'tabs.notes': 'Note',
        'tabs.details': 'Dettagli',
        'tabs.feats': 'Talenti',
        'tabs.actions': 'Azioni',

        // Builder Desktop
        'builder.ancestryFeat': 'Talento di Stirpe',
        'builder.classFeat': 'Talento di Classe',
        'builder.archetypeFeat': 'Talento di Archetipo',
        'builder.abilityBoost': 'Incremento di Caratteristica',
        'builder.futureChoices': 'Scelte future...',
        'builder.noWeapons': 'Nessuna arma equipaggiata. Aggiungi un\'arma per iniziare.',
        'builder.addWeaponHint': 'Aggiungi un\'arma per calcolare i bonus d\'attacco.',
        'builder.noGear': 'Nessun equipaggiamento nell\'inventario.',
        'builder.addGearHint': 'Aggiungi equipaggiamento, consumabili e tesori.',
        'builder.noSpellcasting': 'Questo personaggio non è un incantatore.',
        'builder.noSpellsKnown': 'Nessun incantesimo conosciuto.',
        'builder.noFeats': 'Nessun talento selezionato.',
        'builder.addFeatHint': 'Seleziona i talenti dalla barra laterale.',
        'builder.noNotes': 'Nessuna nota.',
        'builder.noResistances': 'Nessuna',

        // Stats Extended
        'stats.armorClass': 'Classe Armatura',
        'stats.attack': 'Attacco',
        'stats.damage': 'Danni',
        'stats.hands': 'Mani',
        'stats.bulk': 'Ingombro',
        'stats.currency': 'Valuta',
        'stats.invested': 'Investiti',
        'stats.base': 'Base',
        'stats.proficiency': 'Comp',
        'stats.armor': 'Armatura',
        'stats.savingThrows': 'Tiri Salvezza',
        'stats.resistances': 'Resistenze e Immunità',
        'stats.level': 'Livello',
        'stats.tradition': 'Tradizione',
        'stats.spellAttack': 'Attacco Incantesimo',
        'stats.spellDC': 'CD Incantesimo',
        'stats.focusPoints': 'Punti Focalizzazione',
        'stats.spellSlots': 'Slot Incantesimo',
        'stats.rank': 'Grado',
        'stats.knownSpells': 'Incantesimi Conosciuti',

        // Saves
        'saves.fortitude': 'Tempra',
        'saves.reflex': 'Riflessi',
        'saves.will': 'Volontà',

        // Actions Extended
        'actions.strike': 'Colpire',
        'actions.details': 'Dettagli',
        'actions.addGear': 'Aggiungi Equip.',
        'actions.addSpell': 'Aggiungi Incantesimo',
        'actions.cast': 'Lancia',
        'actions.action': 'Azione',
        'actions.actions': 'Azioni',
        'actions.free': 'Gratuita',
        'actions.reaction': 'Reazione',

        // Filters
        'filters.all': 'Tutti',
        'filters.cost': 'Costo',
        'filters.category': 'Categoria',
        'filters.basic': 'Base',
        'filters.skill': 'Abilità',
        'filters.class': 'Classe',
        'filters.interaction': 'Interazione',
        'filters.offense': 'Offesa',
        'filters.movement': 'Movimento',
        'filters.feat': 'Talento',
        'filters.pet': 'Animale',

        // Status
        'status.encumbered': 'Ingombrato',
        'status.overloaded': 'Sovraccarico',
        'status.worn': 'Indossato',

        // Feats Categories
        'feats.ancestry': 'Talenti di Stirpe',
        'feats.class': 'Talenti di Classe',
        'feats.general': 'Talenti Generali',
        'feats.skill': 'Talenti di Abilità',
        'feats.bonus': 'Talenti Bonus',
        'feats.total': 'totali',

        // Reference
        'reference.attackBonus': 'Riferimento Bonus Attacco',

        // Character
        'character.name': 'Nome',
        'character.player': 'Giocatore',
        'character.notes': 'Note',
        'character.alignment': 'Allineamento',
        'character.selectAlignment': 'Seleziona Allineamento',

        // Weapons
        'weapons.attack': 'Attacco',
        'weapons.firstAttack': 'Primo Attacco',
        'weapons.secondAttack': 'Secondo Attacco (MAP)',
        'weapons.thirdAttack': 'Terzo Attacco (MAP)',
        'weapons.twoHandToggle': 'Modalità a Due Mani',
        'weapons.map': 'MAP (Penalità Attacchi Multipli)',
        'weapons.options': 'Opzioni Arma',
        'weapons.fundamentalRunes': 'Rune Fondamentali',
        'weapons.potencyRune': 'Runa Potenza',
        'weapons.potency': 'Potenza',
        'weapons.greaterPotency': 'Grande Potenza',
        'weapons.majorPotency': 'Potenza Maggiore',
        'weapons.strikingRune': 'Runa Colpitore',
        'weapons.striking': 'Colpitore',
        'weapons.greaterStriking': 'Grande Colpitore',
        'weapons.majorStriking': 'Colpitore Maggiore',
        'weapons.propertyRunes': 'Rune di Proprietà',
        'weapons.enterRuneName': 'Inserisci nome runa...',
        'weapons.addPropertyRune': 'Aggiungi Runa di Proprietà',
        'weapons.materialPhysical': 'Materiale e Fisico',
        'weapons.material': 'Materiale',
        'weapons.isLarge': 'Arma Grande',
        'weapons.bulkOverride': 'Sovrascrivi Ingombro',
        'weapons.advancedCustomization': 'Personalizzazione Avanzata',
        'weapons.attackAbility': 'Caratteristica Attacco',
        'weapons.auto': 'Auto (Predefinito)',
        'weapons.customName': 'Nome Personalizzato',
        'weapons.bonusAttack': 'Bonus Attacco',
        'weapons.bonusDamage': 'Bonus Danno',
        'weapons.customDamageType': 'Tipo Danno Personalizzato',
        'weapons.criticalSpecialization': 'Specializzazione Critica',
        'weapons.totalPrice': 'Prezzo Totale',
        'weapons.none': 'Nessuno',
        'weapons.rollAttack': 'Tira Attacco',
        'materials.coldIron': 'Ferro Freddo',
        'materials.silver': 'Argento',
        'materials.adamantine': 'Adamantio',
        'materials.orichalcum': 'Oricalco',
        'materials.mithral': 'Mitrile',

        // Armor
        'armor.potencyRune': 'Runa Potenza Armatura',
        'armor.resilientRune': 'Runa Resiliente',
        'armor.propertyRunes': 'Rune di Proprietà',
        'armor.addPropertyRune': 'Aggiungi Runa di Proprietà',
        'armor.advancedCustomization': 'Personalizzazione Avanzata',
        'armor.customName': 'Nome Personalizzato',
        'armor.bonusAC': 'Bonus CA',
        'armor.checkPenaltyOverride': 'Sovrascrivi Penalità Tiri',
        'armor.speedPenaltyOverride': 'Sovrascrivi Penalità Velocità',
        'armor.dexCapOverride': 'Sovrascrivi Limite DES',
        'armor.totalPrice': 'Prezzo Totale',
        'armor.options': 'Opzioni Armatura',

        // Shield
        'shield.reinforcingRune': 'Runa Rinforzo',
        'shield.propertyRunes': 'Rune di Proprietà',
        'shield.addPropertyRune': 'Aggiungi Runa di Proprietà',
        'shield.advancedCustomization': 'Personalizzazione Avanzata',
        'shield.customName': 'Nome Personalizzato',
        'shield.hardnessOverride': 'Sovrascrivi Durezza',
        'shield.maxHPOverride': 'Sovrascrivi PF Massimi',
        'shield.currentHP': 'PF Attuali',
        'shield.broken': 'Rotto',
        'shield.totalPrice': 'Prezzo Totale',
        'shield.options': 'Opzioni Scudo',

        // Defense
        'defense.resistances': 'Resistenze e Immunità',
        'defense.noResistances': 'Nessuna',
        'defense.addResistance': 'Aggiungi Resistenza',
        'defense.addImmunity': 'Aggiungi Immunità',
        'defense.type': 'Tipo',
        'defense.value': 'Valore',
        'defense.selectType': 'Seleziona tipo...',

        // Spellcasting
        'spellcasting.spellDC': 'CD Incantesimo',
        'spellcasting.spellAttack': 'Tiro Incantesimo',
        'spellcasting.tradition': 'Tradizione',
        'spellcasting.keyAbility': 'Caratteristica Chiave',

        // Equipment
        'equipment.armor': 'Armatura',
        'equipment.shield': 'Scudo',
        'actions.equipArmor': 'Equipaggia Armatura',
        'actions.equipShield': 'Equipaggia Scudo',
        'actions.equip': 'Equipaggia',
        'actions.wield': 'Impugna',
        'actions.unequip': 'Rimuovi',
        'browser.equipment': 'Browser Equipaggiamento',
        'browser.search': 'Cerca...',
        'browser.selectItem': 'Seleziona un oggetto per vedere i dettagli',

        // Pets & Companions
        'pets.title': 'Famigli & Compagni',
        'pets.empty': 'Nessun famiglio o compagno ancora. Aggiungi un famiglio, compagno animale o eidolon al tuo personaggio.',
        'pets.add': 'Aggiungi Famiglio',
        'pets.type': 'Tipo',
        'pets.level': 'Livello',
        'pets.hp': 'PF',
        'pets.ac': 'CA',
        'pets.perception': 'Percezione',
        'pets.saves': 'Tiri Salvezza',
        'pets.speed': 'Velocità',
        'pets.attacks': 'Attacchi',
        'pets.abilities': 'Abilità',
        'pets.evolutions': 'Evoluzioni',
        'pets.notes': 'Note',
        'pets.edit': 'Modifica',
        'pets.delete': 'Elimina',
        'pets.confirmDelete': 'Sei sicuro di voler rimuovere questo famiglio?',
        'pets.familiar': 'Famiglio',
        'pets.animalCompanion': 'Compagno Animale',
        'pets.eidolon': 'Eidolon',
        'pets.selectType': 'Seleziona Tipo Famiglio',
        'pets.enterName': 'Inserisci il nome...',
        'pets.animal.companionType': 'Tipo Compagno',
        'pets.animal.size': 'Taglia',
        'pets.eidolon.evolutionPoints': 'Punti Evoluzione',
        'pets.eidolon.sharesHP': 'Condivide PF con l\'Invocatore',
        'pets.familiar.abilities': 'Abilità del Famiglio',
        'pets.familiar.selectAbilities': 'Seleziona fino a 2 abilità',
        'pets.familiar.addAbility': 'Aggiungi Abilità',
        'pets.stats': 'Statistiche',
        'pets.masterLevel': 'Livello Padrone',
        'pets.conMod': 'Mod COST',
        'pets.actions.petActions': 'Azioni Famiglio',
        'pets.actions.familiarAbility': 'Usa Abilità Famiglio',
        'pets.actions.companionAttack': 'Attacco Compagno',
        'pets.actions.eidolanEvolution': 'Usa Evoluzione',
        'pets.size.tiny': 'Minuscolo',
        'pets.size.small': 'Piccolo',
        'pets.size.medium': 'Medio',
        'pets.size.large': 'Grande',
        'pets.proficiency.untrained': 'Non Addestrato',
        'pets.proficiency.trained': 'Addestrato',
        'pets.proficiency.expert': 'Esperto',
        'pets.proficiency.master': 'Maestro',
        'pets.proficiency.legendary': 'Leggendario',

        // Crafting & Formula Book
        'crafting.title': 'Creazione',
        'crafting.formulas': 'Libro delle Formule',
        'crafting.projects': 'Progetti di Creazione',
        'crafting.dailyItems': 'Item Giornalieri',
        'crafting.addFormula': 'Aggiungi Formula',
        'crafting.newProject': 'Nuovo Progetto',
        'crafting.startProject': 'Inizia Creazione',
        'crafting.daysSpent': 'Giorni Lavorati',
        'crafting.progress': 'Progresso',
        'crafting.targetValue': 'Costo (pm)',
        'crafting.complete': 'Completa',
        'crafting.collectItem': 'Raccogli Oggetto',
        'crafting.addDay': 'Aggiungi Giorno di Lavoro',
        'crafting.bulk': 'Ingombro',
        'crafting.price': 'Prezzo',
        'crafting.level': 'Livello',
        'crafting.craftingSuccess': 'Creazione Riuscita!',
        'crafting.craftingError': 'Errore di Creazione',
        'crafting.notEnoughGold': 'Oro insufficiente per completare la creazione',
        'crafting.projectCompleted': 'Progetto completato! Oggetto aggiunto all\'inventario.',
        'crafting.emptyFormulas': 'Nessuna formula appresa ancora.',
        'crafting.emptyProjects': 'Nessun progetto di creazione attivo.',
        'crafting.emptyDailyItems': 'Nessun item giornaliero creato.',
        'crafting.formulaAdded': 'Formula aggiunta al libro.',
        'crafting.formulaRemoved': 'Formula rimossa dal libro.',
        'crafting.confirmComplete': 'Completare questo progetto? Questo dedurrà l\'oro necessario.',
        'crafting.proficiencyBonus': 'Bonus Competenza',
        'crafting.costReduction': 'Riduzione Costo per Giorno',

        // Container System
        'inventory.containers': 'Contenitori',
        'inventory.root': 'Inventario Principale',
        'inventory.moveToContainer': 'Sposta nel Contenitore',
        'inventory.removeFromContainer': 'Rimuovi dal Contenitore',
        'inventory.bulkUsed': 'Ingombro Usato',
        'inventory.bulkMax': 'Massimo Ingombro',
        'inventory.encumbered': 'Ingombrato',
        'inventory.lightItems': 'Oggetti Leggeri',
        'inventory.capacity': 'Capacità',
        'inventory.bulkReduction': 'Riduzione Ingombro',
        'inventory.selectContainer': 'Seleziona Contenitore',

        // Tooltip & Calculation Breakdown
        'tooltip.base': 'Base',
        'tooltip.ability': 'Caratteristica',
        'tooltip.proficiency': 'Competenza',
        'tooltip.item': 'Oggetto',
        'tooltip.buff': 'Buff',
        'tooltip.penalty': 'Penalità',
        'tooltip.total': 'Totale',
        'theme.dark': 'Modalità Scura',
        'theme.light': 'Modalità Chiara',

        // Variant Rules
        'menu.variantRules': 'Regole Varianti',
        'menu.configureVariantRules': 'Configura Regole Varianti',
        'menu.activeVariantRules': 'attive',

        // Focus Points
        'focus.refocusNote': 'Usa Ricalibra durante i preparativi giornalieri per recuperare i Punti Focalizzazione.',
        'actions.spendFocus': 'Spendi Punto Focalizzazione',
        'actions.recoverFocus': 'Recupera Punto Focalizzazione',
        'actions.refocus': 'Ricalibra',
        'actions.spend': 'Spendi',
        'actions.recover': 'Recupera',
        'actions.change': 'Cambia',
        'actions.remove': 'Rimuovi',

        // Rituals
        'tabs.rituals': 'Riti',
        'rituals.browser': 'Browser Riti',
        'rituals.noRituals': 'Nessun rito conosciuto.',
        'rituals.castTime': 'Tempo di Lancio',
        'rituals.primaryCheck': 'Tiro Primario',
        'rituals.secondaryCheck': 'Tiro Secondario',
        'rituals.cost': 'Costo',
        'rituals.primary': 'Primario',
        'rituals.secondary': 'Secondario',
        'actions.browseRituals': 'Sfoglia Riti',
        'actions.learnRitual': 'Impara Rito',
        'actions.removeRitual': 'Rimuovi Rito',
        'rituals.alreadyKnown': 'Già Conosciuto',
        'filter.all': 'Tutti',

        // Magical Items (Staves & Wands)
        'magicalItems.staves': 'Bastoni',
        'magicalItems.wands': 'Bacchette',
        'magicalItems.charges': 'Cariche',
        'magicalItems.spells': 'Incantesimi',
        'magicalItems.prepareStaff': 'Prepara Bastone',
        'magicalItems.prepare': 'Prepara',
        'magicalItems.castFromStaff': 'Lancia dal Bastone',
        'magicalItems.dailyUses': 'Usi Giornalieri',
        'magicalItems.depleted': 'Esaurita',
        'magicalItems.castFromWand': 'Lancia dalla Bacchetta',
        'magicalItems.cast': 'Lancia',
        'magicalItems.overchargeRisk': 'Rischio Sovraccarico',
        'magicalItems.castOvercharge': 'Lancia (Sovraccarico)',
        'magicalItems.noMagicalItems': 'Nessun oggetto magico equipaggiato.',
        'magicalItems.addStavesWands': 'Aggiungi Bastoni o Bacchette al tuo equipaggiamento per gestire le loro proprietà magical.',
        'magicalItems.overchargeWarning': 'Avviso Sovraccarico',
        'magicalItems.overchargeWarningText': 'Usare questa bacchetta di nuovo oggi richiede di sovraccaricarla. Questo rischia di danneggiare o distruggere la bacchetta.',
        'magicalItems.overchargeDC': 'CD Sovraccarico',
        'magicalItems.onFailure': 'Su Fallimento',
        'magicalItems.wandTakesDamage': 'La bacchetta subisce danni',
        'magicalItems.onCriticalFailure': 'Su Fallimento Critico',
        'magicalItems.wandDestroyed': 'La bacchetta viene distrutta',
        'magicalItems.riskOvercharge': 'Rischia Sovraccarico',

        // Search & Browse
        'search.placeholder': 'Cerca...',
        'actions.browseSpells': 'Sfoglia Incantesimi',
        'actions.learnSpell': 'Impara Incantesimo',

        // Dice Roller
        'dice.roll': 'Tira',
        'dice.total': 'Totale',
        'dice.history': 'Storico Tiri',
        'dice.clearHistory': 'Cancella Storico',
        'dice.noRolls': 'Nessun tiro ancora.',
        'dice.rolls': 'tiri',
        'dice.clickToClose': 'Clicca ovunque per chiudere',
        'dice.criticalSuccess': 'SUCCESSO CRITICO!',
        'dice.criticalFailure': 'FALLIMENTO CRITICO!',
        'dice.attackRoll': 'Tiro per Colpire',
        'dice.damageRoll': 'Tiro Danni',
        'dice.saveRoll': 'Tiro Salvezza',
        'dice.skillCheck': 'Tiro Abilità',
        'dice.perceptionCheck': 'Tiro Percezione',
        'dice.initiative': 'Iniziativa',
        'dice.crit': 'Critico',
        'dice.3dEnable': 'Attiva Dadi 3D',
        'dice.3dDisable': 'Disattiva Dadi 3D',

        // Biography & Appearance
        'biography.title': 'Biografia & Aspetto',
        'biography.quickStats': 'Statistiche Rapide',
        'biography.age': 'Età',
        'biography.gender': 'Genere',
        'biography.pronouns': 'Pronomi',
        'biography.height': 'Altezza',
        'biography.weight': 'Peso',
        'biography.ethnicity': 'Etnia',
        'biography.nationality': 'Nazionalità',
        'biography.birthplace': 'Luogo di nascita',
        'biography.appearance': 'Aspetto Fisico',
        'biography.personality': 'Personalità & Comportamento',
        'biography.beliefs': 'Credenze & Filosofia',
        'biography.likes': 'Piace',
        'biography.dislikes': 'Non piace',
        'biography.catchphrases': 'Frasi Memorabili',
        'biography.avatarUrl': 'URL Immagine',
        'biography.genderPlaceholder': 'Maschio, Femmina, Non-binario...',
        'biography.ethnicityPlaceholder': 'Umano, Elfo, Nano...',
        'biography.nationalityPlaceholder': 'Cheliax, Taldor, Varisia...',
        'biography.birthplacePlaceholder': 'Magnimar, Sandpoint, Westcrown...',
        'biography.appearancePlaceholder': 'Descrivi l\'aspetto fisico del tuo personaggio... Colore dei capelli, occhi, tratti distintivi, stile di abbigliamento, ecc.',
        'biography.personalityPlaceholder': 'Descrivi la personalità del tuo personaggio... Tratti, maniere, come interagisce con gli altri, ecc.',
        'biography.beliefsPlaceholder': 'Descrivi le credenze del tuo personaggio... Visioni religiose, filosofia, codice morale, ecc.',
        'biography.likesPlaceholder': 'Cosa piace al tuo personaggio?',
        'biography.dislikesPlaceholder': 'Cosa odia o teme il tuo personaggio?',
        'biography.catchphrasesPlaceholder': 'Frase famose, modi di dire, o cose che il tuo personaggio dice spesso...',

        // Deity
        'deity.selectDeity': 'Seleziona Divinità',
        'deity.searchDeities': 'Cerca divinità...',
        'deity.allFonts': 'Tutti i Fonti',
        'deity.fontHeal': 'Guarigione',
        'deity.fontHarm': 'Danno',
        'deity.fontBoth': 'Entrambi',
        'deity.font': 'Fonte',
        'deity.favoredWeapon': 'Arma Preferita',
        'deity.skill': 'Abilità Divina',
        'deity.domains': 'Domini',
        'deity.edicts': 'Editti',
        'deity.anathema': 'Anatema',
        'deity.select': 'Seleziona',
        'deity.setYourAlignment': 'Imposta prima il tuo allineamento',

        // Specialization
        'specialization.title': 'Specializzazione di Classe',
        'specialization.notAvailable': 'Questa classe non ha una opzione di specializzazione.',
        'specialization.selectPrompt': 'Seleziona una specializzazione dalla lista per vedere i dettagli.',

        // Commander
        'commander.tactics': 'Tattiche',
        'commander.selectTactics': 'Seleziona Tattiche',
        'commander.tier': 'Grado',
        'commander.category': 'Categoria',
        'commander.allTiers': 'Tutti i Gradi',
        'commander.basic': 'Base (Livello 1+)',
        'commander.expert': 'Esperto (Livello 7+)',
        'commander.master': 'Maestro (Livello 15+)',
        'commander.legendary': 'Leggendario (Livello 19+)',
        'commander.allCategories': 'Tutte le Categorie',
        'commander.mobility': 'Mobilità',
        'commander.offensive': 'Offensiva',
        'commander.all': 'Tutte',
        'commander.prepared': 'Preparate',
        'commander.known': 'Note',
        'commander.noTacticsAvailable': 'Nessuna tattica disponibile con i filtri correnti.',
        'commander.noPreparedTactics': 'Nessuna tattica preparata.',
        'commander.noTactics': 'Nessuna tattica disponibile.',
        'commander.tacticsSelected': 'tattiche selezionate',
        'commander.prepare': 'Prepara',
        'commander.unprepare': 'Rimuovi',
        'commander.cost': 'Costo',
        'commander.tacticsBasic': 'Tattiche Base',
        'commander.tacticsExpert': 'Tattiche Esperte',
        'commander.tacticsMaster': 'Tattiche Maestro',
        'commander.tacticsLegendary': 'Tattiche Leggendarie',
        'commander.dailyTactics': 'Tattiche Giornaliere',
        'commander.noKnownTactics': 'Nessuna tattica selezionata. Vai alla selezione livello per scegliere le tue tattiche.',

        // Resources
        'resources.title': 'Risorse',
        'resources.add': 'Aggiungi',
        'resources.addResource': 'Aggiungi Risorsa Personalizzata',
        'resources.name': 'Nome',
        'resources.namePlaceholder': 'es. Canale Energetico, Furia, ecc.',
        'resources.maxUses': 'Utilizzi Massimi',
        'resources.frequency': 'Frequenza',
        'resources.daily': 'Giornaliero',
        'resources.perEncounter': 'Per Incontro',
        'resources.resetDaily': 'Resetta tutte le risorse giornaliere',
        'resources.resetDailyShort': 'Reset Giornaliero',
        'resources.resetEncounter': 'Resetta tutte le risorse per incontro',
        'resources.resetEncounterShort': 'Reset Incontro',
        'resources.empty': 'Nessuna risorsa personalizzata. Aggiungi abilità o oggetti con utilizzi limitati.',
        'resources.loadClassResources': 'Carica risorse automatiche della classe',
        'resources.loadClassResourcesShort': 'Carica Risorse Classe',

        // Notes
        'notes.edit': 'Modifica',
        'notes.preview': 'Anteprima',
        'notes.startTyping': 'Inizia a scrivere...',
        'notes.addSection': 'Aggiungi Sezione',
        'notes.sectionTitle': 'Titolo Sezione:',

        // Cineticista
        'kineticist.gatesThreshold': "Soglia del Portale",
        'kineticist.choosePath': 'Scegli il Tuo Percorso',
        'kineticist.gatesThresholdDescription': 'A questo livello, la tua connessione con i piani elementali si approfondisce. Scegli come espandere i tuoi poteri:',
        'kineticist.expandThePortal': 'Espandi il Portale',
        'kineticist.expandThePortalDesc': 'Scegli una giunzione dai tuoi elementi attuali, ottenendo accesso a nuovi impulsi.',
        'kineticist.learnImpulse': 'Impara Impulso',
        'kineticist.learnImpulseDesc': 'Impara un nuovo impulso dai tuoi elementi attuali',
        'kineticist.learnImpulseDescFull': 'Impara un nuovo talento impulso dai tuoi elementi attuali. Puoi selezionare questo impulso nella sezione talenti.',
        'kineticist.learnImpulseDescription': 'Potrai selezionare un nuovo talento impulso dai tuoi elementi attuali nella selezione dei talenti.',
        'kineticist.forkThePath': 'Dirama il Percorso',
        'kineticist.forkThePathDesc': 'Scegli un nuovo elemento e ottieni 1 impulso',
        'kineticist.forkThePathFullDescription': 'Stai scegliendo di espandere il tuo dominio elementale aggiungendo un nuovo elemento.',
        'kineticist.selectJunctionPrompt': 'Seleziona 1 giunzione dai tuoi elementi attuali.',
        'kineticist.currentElements': 'Elementi Attuali',
        'kineticist.selected': 'Selezionato',
        'kineticist.newElement': 'Nuovo Elemento',
        'kineticist.selectedImpulse': 'Impulso Selezionato',
        'kineticist.selectNewElement': 'Seleziona Nuovo Elemento',
        'kineticist.selectImpulse': 'Seleziona 1 Impulso',
        'kineticist.availableImpulses': 'Impulsi Disponibili',
        'kineticist.junctionSelected': 'giunzione selezionata',
        'kineticist.impulseFeats': 'Talenti Impulso',

        // Gear Panel - Restore and Swap
        'gear.restore': 'Ripristina',
        'gear.swap': 'Scambia',
        'gear.restoreToDefense': 'Ripristina in Difesa',
        'gear.swapWithDefense': 'Scambia con Difesa',
        'gear.alreadyEquippedWarning': 'Già Equipaggiato',
        'gear.armorAlreadyEquipped': 'C\'è già un\'armatura equipaggiata nello slot Difesa. Rimuovila prima di ripristinare questa.',
        'gear.shieldAlreadyEquipped': 'C\'è già uno scudo equipaggiato nello slot Difesa. Rimuovilo prima di ripristinare questo.',
        'gear.restoreSuccess': 'Ripristinato nello slot Difesa',
        'actions.stow': 'Riponi',
    }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('pf2e-language');
        return (saved as Language) || 'en';
    });

    const setLanguage = useCallback((lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('pf2e-language', lang);
    }, []);

    const toggleLanguage = useCallback(() => {
        setLanguage(language === 'en' ? 'it' : 'en');
    }, [language, setLanguage]);

    const t = useCallback((key: string): string => {
        return translations[language][key] || key;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}

// Helper to get localized name from entity (name/nameIt)
export function useLocalizedName() {
    const { language } = useLanguage();
    return useCallback((entity: { name: string; nameIt?: string }) => {
        return language === 'it' && entity.nameIt ? entity.nameIt : entity.name;
    }, [language]);
}

// Helper to get localized description from entity
export function useLocalizedDescription() {
    const { language } = useLanguage();
    return useCallback((entity: { description: string; descriptionIt?: string }) => {
        return language === 'it' && entity.descriptionIt ? entity.descriptionIt : entity.description;
    }, [language]);
}
